### ISSUE TITLE
`navbar-light` and maybe other light css classes not correctly inverted.

### ISSUE THREAD

**Issue by dessalines** [SaberTooth-Studios/NordTheme-Bootstrap#3]
I just tried out this for lemmy, and `navbar-light` isn't correctly inverted for this dark theme. For dark themes, navbar-light and navbar-dark have their colors switched. This is the standard for all dark themes you'll find.

![image](https://user-images.githubusercontent.com/930215/146218436-ea7b98f7-35a3-4b72-8c66-991de7e85d03.png)

**Comment by SaberTooth-Studios** [comment]
Hewwo There, @dessalines! 👋

Thanks for opening this issue! I'm currently switching out the dark and light, as you said, and a fix will be made soon!

Thanks, and Cya Later 😸

**Comment by SaberTooth-Studios** [comment]
Hai Again! 👋

I've fixed the problem, see pull request #4 for more details, and released a fix for this issue! 
Thanks for spotting the error and posting this issue! 🥰

The latest release, [v1.3.0](https://github.com/SaberTooth-Studios/NordTheme-Bootstrap/releases/tag/v1.3.0), should fix the problem, if theres more that needs to be fixed then please tell me and I'll fix it as soon as I can!

Cya later! 😸

**Comment by dessalines** [comment]
Thanks!

**Comment by SaberTooth-Studios** [comment]
No problem! And, thank _you_ for reporting this issue! 😸
